// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[characterToken-0]
	_ = x[startTagToken-1]
	_ = x[endTagToken-2]
	_ = x[endOfFileToken-3]
	_ = x[commentToken-4]
	_ = x[docTypeToken-5]
}

const _tokenType_name = "characterTokenstartTagTokenendTagTokenendOfFileTokencommentTokendocTypeToken"

var _tokenType_index = [...]uint8{0, 14, 27, 38, 52, 64, 76}

func (i tokenType) String() string {
	if i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
